import { z } from '@kbn/zod';
export type AttackDiscoveryFindInternalResponse = z.infer<typeof AttackDiscoveryFindInternalResponse>;
export declare const AttackDiscoveryFindInternalResponse: z.ZodObject<{
    connector_names: z.ZodArray<z.ZodString, "many">;
    data: z.ZodArray<z.ZodObject<{
        alertIds: z.ZodArray<z.ZodString, "many">;
        alertRuleUuid: z.ZodOptional<z.ZodString>;
        alertWorkflowStatus: z.ZodOptional<z.ZodString>;
        connectorId: z.ZodString;
        connectorName: z.ZodString;
        alertStart: z.ZodOptional<z.ZodString>;
        alertUpdatedAt: z.ZodOptional<z.ZodString>;
        alertUpdatedByUserId: z.ZodOptional<z.ZodString>;
        alertUpdatedByUserName: z.ZodOptional<z.ZodString>;
        alertWorkflowStatusUpdatedAt: z.ZodOptional<z.ZodString>;
        detailsMarkdown: z.ZodString;
        entitySummaryMarkdown: z.ZodOptional<z.ZodString>;
        generationUuid: z.ZodString;
        id: z.ZodString;
        mitreAttackTactics: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        replacements: z.ZodOptional<z.ZodObject<{}, "strip", z.ZodString, z.objectOutputType<{}, z.ZodString, "strip">, z.objectInputType<{}, z.ZodString, "strip">>>;
        riskScore: z.ZodOptional<z.ZodNumber>;
        summaryMarkdown: z.ZodString;
        timestamp: z.ZodEffects<z.ZodString, string, string>;
        title: z.ZodString;
        userId: z.ZodOptional<z.ZodString>;
        userName: z.ZodOptional<z.ZodString>;
        users: z.ZodOptional<z.ZodArray<z.ZodObject<{
            id: z.ZodOptional<z.ZodString>;
            name: z.ZodOptional<z.ZodString>;
        }, "strip", z.ZodTypeAny, {
            id?: string | undefined;
            name?: string | undefined;
        }, {
            id?: string | undefined;
            name?: string | undefined;
        }>, "many">>;
        assignees: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    }, "strip", z.ZodTypeAny, {
        title: string;
        id: string;
        timestamp: string;
        connectorId: string;
        alertIds: string[];
        connectorName: string;
        detailsMarkdown: string;
        generationUuid: string;
        summaryMarkdown: string;
        users?: {
            id?: string | undefined;
            name?: string | undefined;
        }[] | undefined;
        tags?: string[] | undefined;
        replacements?: z.objectOutputType<{}, z.ZodString, "strip"> | undefined;
        alertRuleUuid?: string | undefined;
        alertWorkflowStatus?: string | undefined;
        alertStart?: string | undefined;
        alertUpdatedAt?: string | undefined;
        alertUpdatedByUserId?: string | undefined;
        alertUpdatedByUserName?: string | undefined;
        alertWorkflowStatusUpdatedAt?: string | undefined;
        entitySummaryMarkdown?: string | undefined;
        mitreAttackTactics?: string[] | undefined;
        riskScore?: number | undefined;
        userId?: string | undefined;
        userName?: string | undefined;
        assignees?: string[] | undefined;
    }, {
        title: string;
        id: string;
        timestamp: string;
        connectorId: string;
        alertIds: string[];
        connectorName: string;
        detailsMarkdown: string;
        generationUuid: string;
        summaryMarkdown: string;
        users?: {
            id?: string | undefined;
            name?: string | undefined;
        }[] | undefined;
        tags?: string[] | undefined;
        replacements?: z.objectInputType<{}, z.ZodString, "strip"> | undefined;
        alertRuleUuid?: string | undefined;
        alertWorkflowStatus?: string | undefined;
        alertStart?: string | undefined;
        alertUpdatedAt?: string | undefined;
        alertUpdatedByUserId?: string | undefined;
        alertUpdatedByUserName?: string | undefined;
        alertWorkflowStatusUpdatedAt?: string | undefined;
        entitySummaryMarkdown?: string | undefined;
        mitreAttackTactics?: string[] | undefined;
        riskScore?: number | undefined;
        userId?: string | undefined;
        userName?: string | undefined;
        assignees?: string[] | undefined;
    }>, "many">;
    page: z.ZodNumber;
    per_page: z.ZodOptional<z.ZodNumber>;
    total: z.ZodNumber;
    unique_alert_ids_count: z.ZodNumber;
    unique_alert_ids: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    data: {
        title: string;
        id: string;
        timestamp: string;
        connectorId: string;
        alertIds: string[];
        connectorName: string;
        detailsMarkdown: string;
        generationUuid: string;
        summaryMarkdown: string;
        users?: {
            id?: string | undefined;
            name?: string | undefined;
        }[] | undefined;
        tags?: string[] | undefined;
        replacements?: z.objectOutputType<{}, z.ZodString, "strip"> | undefined;
        alertRuleUuid?: string | undefined;
        alertWorkflowStatus?: string | undefined;
        alertStart?: string | undefined;
        alertUpdatedAt?: string | undefined;
        alertUpdatedByUserId?: string | undefined;
        alertUpdatedByUserName?: string | undefined;
        alertWorkflowStatusUpdatedAt?: string | undefined;
        entitySummaryMarkdown?: string | undefined;
        mitreAttackTactics?: string[] | undefined;
        riskScore?: number | undefined;
        userId?: string | undefined;
        userName?: string | undefined;
        assignees?: string[] | undefined;
    }[];
    page: number;
    total: number;
    connector_names: string[];
    unique_alert_ids_count: number;
    per_page?: number | undefined;
    unique_alert_ids?: string[] | undefined;
}, {
    data: {
        title: string;
        id: string;
        timestamp: string;
        connectorId: string;
        alertIds: string[];
        connectorName: string;
        detailsMarkdown: string;
        generationUuid: string;
        summaryMarkdown: string;
        users?: {
            id?: string | undefined;
            name?: string | undefined;
        }[] | undefined;
        tags?: string[] | undefined;
        replacements?: z.objectInputType<{}, z.ZodString, "strip"> | undefined;
        alertRuleUuid?: string | undefined;
        alertWorkflowStatus?: string | undefined;
        alertStart?: string | undefined;
        alertUpdatedAt?: string | undefined;
        alertUpdatedByUserId?: string | undefined;
        alertUpdatedByUserName?: string | undefined;
        alertWorkflowStatusUpdatedAt?: string | undefined;
        entitySummaryMarkdown?: string | undefined;
        mitreAttackTactics?: string[] | undefined;
        riskScore?: number | undefined;
        userId?: string | undefined;
        userName?: string | undefined;
        assignees?: string[] | undefined;
    }[];
    page: number;
    total: number;
    connector_names: string[];
    unique_alert_ids_count: number;
    per_page?: number | undefined;
    unique_alert_ids?: string[] | undefined;
}>;
