import { z } from '@kbn/zod';
/**
 * An attack discovery that's also an alert (Public API with snake_case)
 */
export type AttackDiscoveryApiAlert = z.infer<typeof AttackDiscoveryApiAlert>;
export declare const AttackDiscoveryApiAlert: z.ZodObject<{
    /**
     * The alert IDs that the attack discovery is based on
     */
    alert_ids: z.ZodArray<z.ZodString, "many">;
    /**
     * The optional kibana.alert.rule.uuid of the rule that generated this attack discovery (not applicable to ad hock runs)
     */
    alert_rule_uuid: z.ZodOptional<z.ZodString>;
    /**
     * The optional kibana.alert.workflow_status of this attack discovery
     */
    alert_workflow_status: z.ZodOptional<z.ZodString>;
    /**
     * The ID of the connector that generated the attack discovery
     */
    connector_id: z.ZodString;
    /**
     * The (human readable) name of the connector that generated the attack discovery
     */
    connector_name: z.ZodString;
    /**
     * The optional time the attack discovery alert was created
     */
    alert_start: z.ZodOptional<z.ZodString>;
    /**
     * The optional time the attack discovery alert was last updated
     */
    alert_updated_at: z.ZodOptional<z.ZodString>;
    /**
     * The optional id of the user who last updated the attack discovery alert
     */
    alert_updated_by_user_id: z.ZodOptional<z.ZodString>;
    /**
     * The optional username of the user who updated the attack discovery alert
     */
    alert_updated_by_user_name: z.ZodOptional<z.ZodString>;
    /**
     * The optional time the attack discovery alert workflow status was last updated
     */
    alert_workflow_status_updated_at: z.ZodOptional<z.ZodString>;
    /**
     * Details of the attack with bulleted markdown that always uses special syntax for field names and values from the source data.
     */
    details_markdown: z.ZodString;
    /**
     * An optional, short (no more than a sentence) summary of the attack discovery featuring only the host.name and user.name fields (when they are applicable), using the same syntax
     */
    entity_summary_markdown: z.ZodOptional<z.ZodString>;
    /**
     * The generation ID of the run that created the attack discovery
     */
    generation_uuid: z.ZodString;
    /**
     * The unique ID of the attack discovery
     */
    id: z.ZodString;
    /**
     * An optional array of MITRE ATT&CK tactic for the attack discovery
     */
    mitre_attack_tactics: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    /**
     * Key-value pairs that are used to replace placeholders in the markdown fields
     */
    replacements: z.ZodOptional<z.ZodObject<{}, "strip", z.ZodString, z.objectOutputType<{}, z.ZodString, "strip">, z.objectInputType<{}, z.ZodString, "strip">>>;
    /**
     * The optional, (but typically populated after generation) risk score of the alert
     */
    risk_score: z.ZodOptional<z.ZodNumber>;
    /**
     * A markdown summary of attack discovery, using the same syntax
     */
    summary_markdown: z.ZodString;
    /**
     * The time the attack discovery was generated
     */
    timestamp: z.ZodEffects<z.ZodString, string, string>;
    /**
     * A title for the attack discovery, in plain text
     */
    title: z.ZodString;
    /**
     * The optional id of the user who generated the attack discovery
     */
    user_id: z.ZodOptional<z.ZodString>;
    /**
     * The optional username of the user who generated the attack discovery, (not applicable to attack discoveries generated by rules)
     */
    user_name: z.ZodOptional<z.ZodString>;
    /**
     * The optional array of users who may view the attack discovery. When empty, (or not present), all users may view the attack discovery.
     */
    users: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        id?: string | undefined;
        name?: string | undefined;
    }, {
        id?: string | undefined;
        name?: string | undefined;
    }>, "many">>;
    /**
     * The optional array of user-IDs who have been assigned the attack
     */
    assignees: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    /**
     * The optional array of tags assigned the attack
     */
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    title: string;
    id: string;
    timestamp: string;
    alert_ids: string[];
    connector_id: string;
    connector_name: string;
    details_markdown: string;
    generation_uuid: string;
    summary_markdown: string;
    users?: {
        id?: string | undefined;
        name?: string | undefined;
    }[] | undefined;
    tags?: string[] | undefined;
    replacements?: z.objectOutputType<{}, z.ZodString, "strip"> | undefined;
    assignees?: string[] | undefined;
    alert_rule_uuid?: string | undefined;
    alert_workflow_status?: string | undefined;
    alert_start?: string | undefined;
    alert_updated_at?: string | undefined;
    alert_updated_by_user_id?: string | undefined;
    alert_updated_by_user_name?: string | undefined;
    alert_workflow_status_updated_at?: string | undefined;
    entity_summary_markdown?: string | undefined;
    mitre_attack_tactics?: string[] | undefined;
    risk_score?: number | undefined;
    user_id?: string | undefined;
    user_name?: string | undefined;
}, {
    title: string;
    id: string;
    timestamp: string;
    alert_ids: string[];
    connector_id: string;
    connector_name: string;
    details_markdown: string;
    generation_uuid: string;
    summary_markdown: string;
    users?: {
        id?: string | undefined;
        name?: string | undefined;
    }[] | undefined;
    tags?: string[] | undefined;
    replacements?: z.objectInputType<{}, z.ZodString, "strip"> | undefined;
    assignees?: string[] | undefined;
    alert_rule_uuid?: string | undefined;
    alert_workflow_status?: string | undefined;
    alert_start?: string | undefined;
    alert_updated_at?: string | undefined;
    alert_updated_by_user_id?: string | undefined;
    alert_updated_by_user_name?: string | undefined;
    alert_workflow_status_updated_at?: string | undefined;
    entity_summary_markdown?: string | undefined;
    mitre_attack_tactics?: string[] | undefined;
    risk_score?: number | undefined;
    user_id?: string | undefined;
    user_name?: string | undefined;
}>;
