import { z } from '@kbn/zod';
/**
 * An attack discovery that's also an alert
 */
export type AttackDiscoveryAlert = z.infer<typeof AttackDiscoveryAlert>;
export declare const AttackDiscoveryAlert: z.ZodObject<{
    /**
     * The alert IDs that the attack discovery is based on
     */
    alertIds: z.ZodArray<z.ZodString, "many">;
    /**
     * The optional kibana.alert.rule.uuid of the rule that generated this attack discovery (not applicable to ad hock runs)
     */
    alertRuleUuid: z.ZodOptional<z.ZodString>;
    /**
     * The optional kibana.alert.workflow_status of this attack discovery
     */
    alertWorkflowStatus: z.ZodOptional<z.ZodString>;
    /**
     * The ID of the connector that generated the attack discovery
     */
    connectorId: z.ZodString;
    /**
     * The (human readable) name of the connector that generated the attack discovery
     */
    connectorName: z.ZodString;
    /**
     * The optional time the attack discovery alert was created
     */
    alertStart: z.ZodOptional<z.ZodString>;
    /**
     * The optional time the attack discovery alert was last updated
     */
    alertUpdatedAt: z.ZodOptional<z.ZodString>;
    /**
     * The optional id of the user who last updated the attack discovery alert
     */
    alertUpdatedByUserId: z.ZodOptional<z.ZodString>;
    /**
     * The optional username of the user who updated the attack discovery alert
     */
    alertUpdatedByUserName: z.ZodOptional<z.ZodString>;
    /**
     * The optional time the attack discovery alert workflow status was last updated
     */
    alertWorkflowStatusUpdatedAt: z.ZodOptional<z.ZodString>;
    /**
     * Details of the attack with bulleted markdown that always uses special syntax for field names and values from the source data.
     */
    detailsMarkdown: z.ZodString;
    /**
     * An optional, short (no more than a sentence) summary of the attack discovery featuring only the host.name and user.name fields (when they are applicable), using the same syntax
     */
    entitySummaryMarkdown: z.ZodOptional<z.ZodString>;
    /**
     * The generation ID of the run that created the attack discovery
     */
    generationUuid: z.ZodString;
    /**
     * The unique ID of the attack discovery
     */
    id: z.ZodString;
    /**
     * An optional array of MITRE ATT&CK tactic for the attack discovery
     */
    mitreAttackTactics: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    /**
     * Key-value pairs that are used to replace placeholders in the markdown fields
     */
    replacements: z.ZodOptional<z.ZodObject<{}, "strip", z.ZodString, z.objectOutputType<{}, z.ZodString, "strip">, z.objectInputType<{}, z.ZodString, "strip">>>;
    /**
     * The optional, (but typically populated after generation) risk score of the alert
     */
    riskScore: z.ZodOptional<z.ZodNumber>;
    /**
     * A markdown summary of attack discovery, using the same syntax
     */
    summaryMarkdown: z.ZodString;
    /**
     * The time the attack discovery was generated
     */
    timestamp: z.ZodEffects<z.ZodString, string, string>;
    /**
     * A title for the attack discovery, in plain text
     */
    title: z.ZodString;
    /**
     * The optional id of the user who generated the attack discovery
     */
    userId: z.ZodOptional<z.ZodString>;
    /**
     * The optional username of the user who generated the attack discovery, (not applicable to attack discoveries generated by rules)
     */
    userName: z.ZodOptional<z.ZodString>;
    /**
     * The optional array of users who may view the attack discovery. When empty, (or not present), all users may view the attack discovery.
     */
    users: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        id?: string | undefined;
        name?: string | undefined;
    }, {
        id?: string | undefined;
        name?: string | undefined;
    }>, "many">>;
    /**
     * The optional array of user-IDs who have been assigned the attack
     */
    assignees: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    /**
     * The optional array of tags assigned the attack
     */
    tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    title: string;
    id: string;
    timestamp: string;
    connectorId: string;
    alertIds: string[];
    connectorName: string;
    detailsMarkdown: string;
    generationUuid: string;
    summaryMarkdown: string;
    users?: {
        id?: string | undefined;
        name?: string | undefined;
    }[] | undefined;
    tags?: string[] | undefined;
    replacements?: z.objectOutputType<{}, z.ZodString, "strip"> | undefined;
    alertRuleUuid?: string | undefined;
    alertWorkflowStatus?: string | undefined;
    alertStart?: string | undefined;
    alertUpdatedAt?: string | undefined;
    alertUpdatedByUserId?: string | undefined;
    alertUpdatedByUserName?: string | undefined;
    alertWorkflowStatusUpdatedAt?: string | undefined;
    entitySummaryMarkdown?: string | undefined;
    mitreAttackTactics?: string[] | undefined;
    riskScore?: number | undefined;
    userId?: string | undefined;
    userName?: string | undefined;
    assignees?: string[] | undefined;
}, {
    title: string;
    id: string;
    timestamp: string;
    connectorId: string;
    alertIds: string[];
    connectorName: string;
    detailsMarkdown: string;
    generationUuid: string;
    summaryMarkdown: string;
    users?: {
        id?: string | undefined;
        name?: string | undefined;
    }[] | undefined;
    tags?: string[] | undefined;
    replacements?: z.objectInputType<{}, z.ZodString, "strip"> | undefined;
    alertRuleUuid?: string | undefined;
    alertWorkflowStatus?: string | undefined;
    alertStart?: string | undefined;
    alertUpdatedAt?: string | undefined;
    alertUpdatedByUserId?: string | undefined;
    alertUpdatedByUserName?: string | undefined;
    alertWorkflowStatusUpdatedAt?: string | undefined;
    entitySummaryMarkdown?: string | undefined;
    mitreAttackTactics?: string[] | undefined;
    riskScore?: number | undefined;
    userId?: string | undefined;
    userName?: string | undefined;
    assignees?: string[] | undefined;
}>;
